<?php
echo '<html>';
echo '';
echo '<head>';
echo '<title>Safe parking</title>';
echo '<link rel="stylesheet" type="text/css" href="../css/feedback.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<!--Header & Navbar part-->';
echo '<div class="cpName">';
echo '<header class="header">';
echo '<h2>Safe Parking </h2>';
echo '';
echo '</header>';
echo '<header class="header2">';
echo '<nav class="navbar">';
echo '<a href="../html/Home.html" class="navLogo">';
echo '<img class="logoImage" src="../images/logo.png">';
echo '';
echo '</a>';
echo '<ul class="navtext">';
echo '<li>';
echo '<a href="../html/Home.html" >Home</a>';
echo '</li>';
echo '<li>';
echo '<a href="../html/help&support.html">Help</a>';
echo '</li>';
echo '<li>';
echo '<a href="../html/Contact.html">Contact us</a>';
echo '</li>';
echo '<li>';
echo '<a href="../html">About</a>';
echo '</li>';
echo '<li class="right">';
echo '<li><li>';
echo '<a href="../html/LoginPage.html">Login</a>';
echo '</li>';
echo '<li>';
echo '<a href="../html/Sign up.html">Sign up</a>';
echo '</li></li>';
echo '</ul>';
echo '';
echo '';
echo '<!--Form part-->';
echo '<!--';
echo '<h3 class="inside1">Provide your feedback</h3>';
echo '<h3 class="inside">';
echo '<div class="form1">';
echo '<form class="form">';
echo '<label class="target">Give your feedback</label><br><br>';
echo '<input type="text" id="feedback" name="feedback" placeholder="Give your feedback..." rows="12" cols="80">';
echo '<textarea name="address" rows="12" cols="80" required placeholder="Give your feedback..."></textarea> <br><br/>';
echo '';
echo '<input type="submit" value="Send">';
echo '</a>';
echo '';
echo '</form>';
echo '</div>';
echo '</h3>';
echo '-->';
echo '';
echo '';
echo '';
echo '<div class="content">';
echo '<div class="container">';
echo '<div class="head">';
echo '<div class="heading"><h1>We would like your feedback</h1></div>';
echo '<div class="close">';
echo '<div class="s s1"></div>';
echo '<div class="s s2"></div>';
echo '</div>';
echo '</div>';
echo ' /*got icon packs from third party*/';
echo '<div class="mid">';
echo '<div class="media"><img src="https://cdn-icons-png.flaticon.com/128/3260/3260838.png" alt="angry" value="bad"></div>';
echo '<div class="media"><img src="https://cdn-icons-png.flaticon.com/128/42/42901.png" alt="moderate" value="okay"></div>';
echo '<div class="media"><img src="https://cdn-icons-png.flaticon.com/128/3260/3260877.png" alt="neutral" value="neither"></div>';
echo '<div class="media"><img src="https://cdn-icons-png.flaticon.com/128/569/569501.png" alt="smile" class="active" value="Good"></div>';
echo '<div class="media"><img src="https://cdn-icons-png.flaticon.com/128/1356/1356639.png" alt="happy" value="excellent"></div>';
echo '</div>';
echo '<div class="textarea">';
echo '<p>Your email</p>';
echo '<input type="text" id="email" name="email" placeholder="Enter email..." pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}" required>';
echo '<p>Share your experience</p>';
echo '<textarea name="exp" id="exp" placeholder="Let us know..." value="exp"></textarea>';
echo '</div>';
echo '<div class="end">';
echo '<div class="submission">';
echo '<button class="sub btn">Send</button>';
echo '</div>';
echo '<div class="can">';
echo '<button class="can btn">cancel</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<!--Footer part-->';
echo '<hr class="underLine">';
echo '<a class="icone" href="https://www.facebook.com">';
echo '<img src="..\image\facebook icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://twitter.com/login">';
echo '<img src="..\image\twiter icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://www.instagram.com">';
echo '<img src="..\image\inst icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://myaccount.google.com/profile">';
echo '<img src="..\image\google icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<div class="payiconeSet">';
echo '<a class="payicone" href="https://www.visa.com.lk/pay-with-visa/security/secure-online-shopping.html"><img src="../images/visa icone.jpg" width="30" height="30"></a>';
echo '<a class="payicone" href="https://www.mastercard.com/global/en/personal/find-card-products.html"> <img src="../images/master icone.jpg" width="30" height="30"></a>';
echo '<a class="payicone" href="https://www.paypal.com/signin?returnUri=https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Fsummary&state="><img src="..//images/paypal icone.jpg" width="30" height="30"> </a>';
echo '<a class="payicone" href="https://portal.discover.com/customersvcs/universalLogin/ac_main"><img src="../images/discover icone.jpg" width="30" height="30"></a>';
echo '</div>';
echo '';
echo '<div class="helpicone1">';
echo '<a class="helpicone" href="../html/help&support.html">';
echo '<img src="..\images\help icone.jpg" width="60" height="40">';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="feedbackicone1">';
echo '<a class="feedbackicone" href="../html/feedback.html">';
echo '<img src="..\images\feedback icone.jpg" width="60" height="40">';
echo '</a>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</nav>';
echo '';
echo '';
echo '</header>';
echo '</div>';
echo '</body>';
echo '</html>';
?>