<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<title>Safe parking</title>';
echo '<link rel="stylesheet" type="text/css" href="../css/help&support.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<!--Header & Navbar part-->';
echo '';
echo '<div class="cpName">';
echo '<header class="header">';
echo '<h2>Safe Parking</h2>';
echo '<header class="header2">';
echo '<nav class="navbar">';
echo '<a href="home.html" class="navLogo">';
echo '<img class="logoImage" src="../images/logo.png">';
echo '';
echo '<div class="navbar" style="float: left;">';
echo '<a href="../html/Home.html" >Home</a>';
echo '<a href="../html/help&support.html" >Help</a>';
echo '<a href="../html/Contact.html" >Contact us</a>';
echo '<a href="" >About</a>';
echo '';
echo '</div>';
echo '<div class="navbar" style="float: right;">';
echo '<a href="../html/LoginPage.html" >Login</a>';
echo '<a href="../html/Sign up.html" >Sign up</a>';
echo '</div>';
echo '';
echo '<!--Form part-->';
echo '<h3 class="inside1">Help & support</h3>';
echo '<h3 class="inside">';
echo '<div class="form1">';
echo '<div style="float: left;">';
echo '<form class="form" action="../php/help&support.php" method="post">';
echo '<label class="target">Help & support</label><br><br>';
echo '<!--<input type="text" id="feedback" name="feedback" placeholder="Give your feedback..." rows="12" cols="80"> -->';
echo '<textarea name="message" rows="8" cols="50" required placeholder="Give your feedback..." required></textarea> <br><br/>';
echo '<input class="inputStyle" id="checkBox" type="checkbox" onclick="enableButton()">Accept privacy policy and terms.<br/><br/>';
echo '<input type="submit" id="submit" value="Send">';
echo '</form>';
echo '</div>';
echo '<div style="float: right;">';
echo '<form class="form" action="../php/help&support.php" method="post">';
echo 'First name:<br/>';
echo '<input type="text" id="fname" name="firstname" value="First name" required> <br/><br/>';
echo 'E-mail:<br/>';
echo '<input type="email" name="email" value="email" placeholder="abc@gmail.com" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}" required> <br><br/>';
echo 'Subject:<br/>';
echo '<input type="text" name="subject" value="Subject" required> <br/><br/>';
echo '';
echo '</form>';
echo '</div>';
echo '';
echo '';
echo '';
echo '</div>';
echo '</h3>';
echo '';
echo '';
echo '<!--Footer part-->';
echo '<hr class="underLine">';
echo '<a class="icone" href="https://www.facebook.com">';
echo '<img src="..\image\facebook icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://twitter.com/login">';
echo '<img src="..\image\twiter icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://www.instagram.com">';
echo '<img src="..\image\inst icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://myaccount.google.com/profile">';
echo '<img src="..\image\google icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<div class="payiconeSet">';
echo '<a class="payicone" href="https://www.visa.com.lk/pay-with-visa/security/secure-online-shopping.html"><img src="../images/visa icone.jpg" width="30" height="30"></a>';
echo '<a class="payicone" href="https://www.mastercard.com/global/en/personal/find-card-products.html"> <img src="../images/master icone.jpg" width="30" height="30"></a>';
echo '<a class="payicone" href="https://www.paypal.com/signin?returnUri=https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Fsummary&state="><img src="..//images/paypal icone.jpg" width="30" height="30"> </a>';
echo '<a class="payicone" href="https://portal.discover.com/customersvcs/universalLogin/ac_main"><img src="../images/discover icone.jpg" width="30" height="30"></a>';
echo '</div>';
echo '';
echo '<div class="helpicone1">';
echo '<a class="helpicone" href="../html/help&support.html">';
echo '<img src="..\images\help icone.jpg" width="60" height="40">';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="feedbackicone1">';
echo '<a class="feedbackicone" href="../html/feedback.html">';
echo '<img src="..\images\feedback icone.jpg" width="60" height="40">';
echo '</a>';
echo '';
echo '</div>';
echo '';
echo '';
echo '</nav>';
echo '';
echo '';
echo '</header>';
echo '</div>';
echo '</body>';
echo '</html>';
?>