<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<title>Safe parking</title>';
echo '<link rel="stylesheet" type="text/css" href="../css/help&support.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<!--Header & Navbar part-->';
echo '';
echo '<div class="cpName">';
echo '<header class="header">';
echo '<h2>Safe Parking</h2>';
echo '<header class="header2">';
echo '<nav class="navbar">';
echo '<a href="home.html" class="navLogo">';
echo '<img class="logoImage" src="../images/logo.png">';
echo '';
echo '<div class="navbar" style="float: left;">';
echo '<a href="../html/Home.html" >Home</a>';
echo '<a href="../html/help&support.html" >Help</a>';
echo '<a href="../html/Contact.html" >Contact us</a>';
echo '<a href="" >About</a>';
echo '';
echo '</div>';
echo '<div class="navbar" style="float: right;">';
echo '<a href="../html/LoginPage.html" >Login</a>';
echo '<a href="../html/Sign up.html" >Sign up</a>';
echo '</div>';
echo '';
echo '<!--Form part-->';
echo '<h3 class="inside1">Submitted Successfully!</h3>';
echo '</h3>';
echo '';
echo '';
echo '<!--Footer part-->';
echo '<hr class="underLine">';
echo '<a class="icone" href="https://www.facebook.com">';
echo '<img src="..\image\facebook icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://twitter.com/login">';
echo '<img src="..\image\twiter icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://www.instagram.com">';
echo '<img src="..\image\inst icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://myaccount.google.com/profile">';
echo '<img src="..\image\google icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<div class="payiconeSet">';
echo '<a class="payicone" href="https://www.visa.com.lk/pay-with-visa/security/secure-online-shopping.html"><img src="../images/visa icone.jpg" width="30" height="30"></a>';
echo '<a class="payicone" href="https://www.mastercard.com/global/en/personal/find-card-products.html"> <img src="../images/master icone.jpg" width="30" height="30"></a>';
echo '<a class="payicone" href="https://www.paypal.com/signin?returnUri=https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Fsummary&state="><img src="..//images/paypal icone.jpg" width="30" height="30"> </a>';
echo '<a class="payicone" href="https://portal.discover.com/customersvcs/universalLogin/ac_main"><img src="../images/discover icone.jpg" width="30" height="30"></a>';
echo '</div>';
echo '';
echo '<div class="helpicone1">';
echo '<a class="helpicone" href="../html/help&support.html">';
echo '<img src="..\images\help icone.jpg" width="60" height="40">';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="feedbackicone1">';
echo '<a class="feedbackicone" href="../html/feedback.html">';
echo '<img src="..\images\feedback icone.jpg" width="60" height="40">';
echo '</a>';
echo '';
echo '</div>';
echo '';
echo '';
echo '</nav>';
echo '';
echo '';
echo '</header>';
echo '</div>';
echo '</body>';
echo '</html>';
?>