<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<title>Safe parking</title>';
echo '<link rel="stylesheet" type="text/css" href="../css/paymentportal1.css">';
echo '';
echo '';
echo '</head>';
echo '<body>';
echo '';
echo '<script src="../js/paymentportal1.js"></script>';
echo '';
echo '<!--Header & Navbar part-->';
echo '';
echo '<div class="cpName">';
echo '<header class="header">';
echo '<h2>Pay here</h2>';
echo '<header class="header2">';
echo '<nav class="navbar">';
echo '<a href="home.html" class="navLogo">';
echo '<img class="logoImage" src="../images/logo.png">';
echo '';
echo '<div class="navbar" style="float: left;">';
echo '<a href="../html/Home.html" >Home</a>';
echo '<a href="../html/help&support.html" >Help</a>';
echo '<a href="../html/Contact.html" >Contact us</a>';
echo '<a href="" >About</a>';
echo '';
echo '</div>';
echo '<div class="navbar" style="float: right;">';
echo '<a href="../html/LoginPage.html" >Login</a>';
echo '<a href="../html/Sign up.html" >Sign up</a>';
echo '</div>';
echo '';
echo '<!--Form part-->';
echo '<div class="w-96 mx-auto border border-gray-400 rounded-lg">';
echo '';
echo '<div class="w-full h-auto p-4 flex items-center border-b border-gray-400">';
echo '<h1 class="w-full">Credit Card</h1></br>';
echo '<!--<a href="" class="w-full text-right text-sm font-semibold text-indigo-700">Other payment methods</a> -->';
echo '</div>';
echo '';
echo '<div class="w-full h-auto p-4">';
echo '<form action="#">';
echo '';
echo '<div class="mb-4 px-3 py-1 bg-white rounded-sm border border-gray-300 focus-within:text-gray-900 focus-within:border-gray-500">';
echo '<label for="cc-name" class="text-xs tracking-wide uppercase font-semibold">Name on card</label>';
echo '<input id="cc-name" type="text" name="cc-name" class="w-full h-8 focus:outline-none" placeholder="e.g. Nandun Godage"></br></br>';
echo '</div>';
echo '';
echo '<div class="mb-4 px-3 py-1 bg-white rounded-sm border border-gray-300 focus-within:text-gray-900 focus-within:border-gray-500">';
echo '<label for="cc-number" class="text-xs tracking-wide uppercase font-semibold">Credit card number</label>';
echo '<input id="cc-number" type="text" name="cc-number" class="w-full h-8 focus:outline-none" placeholder="16-digit card number"></br></br>';
echo '</div>';
echo '';
echo '<div class="flex mb-4 px-3 py-1 bg-white rounded-sm border border-gray-300 focus-within:border-gray-500">';
echo '<div class="w-full focus-within:text-gray-900">';
echo '</t><label for="" class="text-xs tracking-wide uppercase font-semibold">Card expiry</label>';
echo '<input id="cc-expiry" type="text"  name="cc-exp" class="w-full h-8 focus:outline-none" placeholder="MM / YYYY"></br></br>';
echo '</div>';
echo '';
echo '<div class="w-auto focus-within:text-gray-900">';
echo '<label for="" class="text-xs tracking-wide uppercase font-semibold">CVV</label>';
echo '<input id="cc-cvv" type="text" name="cc-cvv" class="w-full h-8 focus:outline-none" maxlength="3"></br></br>';
echo '</div>';
echo '</div>';
echo '';
echo '<button class="h-16 w-full rounded-sm bg-indigo-600 tracking-wide font-semibold text-white hover:bg-indigo-700 focus:ring-2 focus:ring-indigo-600">Confirm Payment</button></br></br>';
echo '';
echo '</form>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<!--Footer part-->';
echo '<hr class="underLine">';
echo '<a class="icone" href="https://www.facebook.com">';
echo '<img src="..\image\facebook icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://twitter.com/login">';
echo '<img src="..\image\twiter icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://www.instagram.com">';
echo '<img src="..\image\inst icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://myaccount.google.com/profile">';
echo '<img src="..\image\google icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<div class="payiconeSet">';
echo '<a class="payicone" href="https://www.visa.com.lk/pay-with-visa/security/secure-online-shopping.html"><img src="../images/visa icone.jpg" width="30" height="30"></a>';
echo '<a class="payicone" href="https://www.mastercard.com/global/en/personal/find-card-products.html"> <img src="../images/master icone.jpg" width="30" height="30"></a>';
echo '<a class="payicone" href="https://www.paypal.com/signin?returnUri=https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Fsummary&state="><img src="..//images/paypal icone.jpg" width="30" height="30"> </a>';
echo '<a class="payicone" href="https://portal.discover.com/customersvcs/universalLogin/ac_main"><img src="../images/discover icone.jpg" width="30" height="30"></a>';
echo '</div>';
echo '';
echo '<div class="helpicone1">';
echo '<a class="helpicone" href="../html/help&support.html">';
echo '<img src="..\images\help icone.jpg" width="60" height="40">';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="feedbackicone1">';
echo '<a class="feedbackicone" href="../html/feedback.html">';
echo '<img src="..\images\feedback icone.jpg" width="60" height="40">';
echo '</a>';
echo '';
echo '</div>';
echo '';
echo '</nav>';
echo '';
echo '';
echo '</header>';
echo '</div>';
echo '</body>';
echo '</html>';
?>