<?php
echo '<html>';
echo '';
echo '<head>';
echo '<title>Safe parking</title>';
echo '<link rel="stylesheet" type="text/css" href="../css/sign up.css">';
echo '<script src="../js/registration.js"></script>';
echo '';
echo '';
echo '</head>';
echo '<body>';
echo '';
echo '<div class="cpName">';
echo '<header class="header">';
echo '<h2>Safe Parking </h2>';
echo '';
echo '</header>';
echo '<header class="header2">';
echo '<nav class="navbar">';
echo '<a href="LoginPage.html" class="navLogo">';
echo '<img class="logoImage" src="..\images\logo.png">';
echo '';
echo '</a>';
echo '<ul class="navtext">';
echo '<li>';
echo '<a href="../html/Home.html" >Home</a>';
echo '</li>';
echo '<li>';
echo '<a href="../html/help&support.html">Help</a>';
echo '</li>';
echo '<li>';
echo '<a href="../html/Contact.html">Contact us</a>';
echo '</li>';
echo '<li>';
echo '<a href="../html">About</a>';
echo '</li>';
echo '<li class="right">';
echo '<li><li>';
echo '<a href="../html/LoginPage.html">Login</a>';
echo '</li>';
echo '<li>';
echo '<a href="../html/Sign up.html">Sign up</a>';
echo '</li></li>';
echo '</ul>';
echo '';
echo '<h3 class="inside">';
echo '<div class="form1">';
echo '<div>';
echo '<form class="form" method ="post" action="signup.php">';
echo '<fieldset>';
echo '<legend>REGISTER</legend>';
echo '<label class="fname">First name</label>';
echo '<input type="text2" id="fName" name="FirstName" >';
echo '';
echo '<label class="lname">Last name</label>';
echo '<input type="text2" id="Lname" name="Lastname" >';
echo '';
echo '<label class="username">Username</label>';
echo '<input type="text2" id="uname" name="UserName" placeholder="Username">';
echo '';
echo '<label class="passwrd">Password</label>';
echo '<input type="text" id="passwrd" name="password" placeholder="Your password..">';
echo '';
echo '<label class="passwrd">Repeat Password</label>';
echo '<input type="text" id="cmpwd" name="Repeatpassword" placeholder="Repeat password..">';
echo '';
echo '<label class="city">City</label>';
echo '<input type="text2" id="city" name="city" >';
echo '';
echo 'State <select>';
echo '<option value="volvo">Volvo</option>';
echo '<option value="saab">Saab</option>';
echo '<option value="mercedes">Mercedes</option>';
echo '<option value="audi">Audi</option>';
echo '<select>';
echo '';
echo '';
echo '<label class="zip">Zip</label>';
echo '<input type="text2" id="zip" name="zip" placeholder="">';
echo '<br>';
echo '<input type="checkbox" id="checkbox" name="A" value="3" onclick="enableButton()"> Agree to term and conditions';
echo '</div>';
echo '<div class="btn">';
echo '<input type="submit" name="submitbn"id="submitbn" value="submit">';
echo '</div>';
echo '';
echo '';
echo '</form>';
echo '</div>';
echo '</h3>';
echo '';
echo '</div>';
echo '';
echo '<hr class="underLine">';
echo '<a class="icone" href="https://www.facebook.com">';
echo '<img src="..\image\facebook icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://twitter.com/login">';
echo '<img src="..\image\twiter icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://www.instagram.com">';
echo '<img src="..\image\inst icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<a class="icone" href="https://myaccount.google.com/profile">';
echo '<img src="..\image\google icone.png" width="30" height="30">';
echo '</a>';
echo '';
echo '<div class="payiconeSet">';
echo '<a class="payicone" href="https://www.visa.com.lk/pay-with-visa/security/secure-online-shopping.html"><img src="../images/visa icone.jpg" width="30" height="30"></a>';
echo '<a class="payicone" href="https://www.mastercard.com/global/en/personal/find-card-products.html"> <img src="../images/master icone.jpg" width="30" height="30"></a>';
echo '<a class="payicone" href="https://www.paypal.com/signin?returnUri=https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Fsummary&state="><img src="..//images/paypal icone.jpg" width="30" height="30"> </a>';
echo '<a class="payicone" href="https://portal.discover.com/customersvcs/universalLogin/ac_main"><img src="../images/discover icone.jpg" width="30" height="30"></a>';
echo '</div>';
echo '';
echo '<div class="helpicone1">';
echo '<a class="helpicone" href="../html/help&support.html">';
echo '<img src="..\images\help icone.jpg" width="60" height="40">';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="feedbackicone1">';
echo '<a class="feedbackicone" href="../html/feedback.html">';
echo '<img src="..\images\feedback icone.jpg" width="60" height="40">';
echo '</a>';
echo '';
echo '</div>';
echo '';
echo '</nav>';
echo '';
echo '';
echo '</header>';
echo '</div>';
echo '</body>';
echo '</html>';
?>